obj-$(CONFIG_ALPS_INPUT)				+= alps-input.o
obj-$(CONFIG_ALPS_INPUT_HSCDTD004A)		+= hscdtd004a_i2c.o
obj-$(CONFIG_ALPS_INPUT_HSCDTD007A)		+= hscdtd007a_i2c.o
obj-$(CONFIG_ALPS_INPUT_BMA150)		+= bma150_i2c.o
obj-$(CONFIG_ALPS_INPUT_BMA222)		+= bma222_i2c.o

